name: UI_TESTS

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g allure-commandline  # Установка Allure CLI

      - name: Run tests
        run: |
          pytest --alluredir=./allure-results

      - name: Generate Allure HTML report
        run: |
          allure generate ./allure-results --clean -o ./allure-report
          echo "baseUrl=/" > ./allure-report/_config.yml  # Фикс для GitHub Pages

      - name: Upload Allure results (raw)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: ./allure-results

      - name: Upload Allure report (HTML)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: ./allure-report

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # Только для main-ветки
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report